### ISSUE TITLE
BST Adjustment Causes Mawqit-Powered Islamic Prayer Times to Display Incorrectly in Home Assistant

### ISSUE THREAD

**Issue by beestonmuslimcentre** [mawaqit/home-assistant#86]
When using Islamic prayer times sourced via Mawqit (or similar services) through Home Assistant, **British Summer Time (BST) adjustments are being erroneously applied twice**, resulting in times being **1 hour ahead** of intended schedules.  

**Problem Breakdown**  
1. **Source Data Issue**: Mawqit/backend services already provide **BST-adjusted times** (e.g., 13:30 for Zuhr instead of the standard 12:30 GMT+0).  
2. **HA Timezone Handling**: Home Assistant's automatic BST conversion **re-applies the +1 hour offset**, creating a **double adjustment** (e.g., 13:30 → 14:30).  
3. **Current Workaround**: Users must manually subtract 1 hour via automations/templates, which is unsustainable for UK users and problematic for other regions observing daylight saving.  

**Steps to Reproduce**  
1. Configure Islamic Prayer Times integration with Mawqit-based data source  
2. Observe prayer times during BST period (March-October)  
3. Compare displayed times against official timetables  

**Expected Behavior**  
Integration should either:  
-  **Disable automatic BST conversion** for prayer time sensors  
-  Provide **configuration toggle** for "Disable daylight saving adjustment"  
-  Offer **manual time offset** field (e.g., "-1 hour" for UK users)  

**Temporary Workaround**  
```yaml
sensor:
  - platform: template
    sensors:
      corrected_dhuhr:
        friendly_name: "Dhuhr (BST Adjusted)"
        value_template: >-
          {% set raw = states('sensor.dhuhr') %}
          {{ (as_timestamp(strptime(raw, '%H:%M')) - 3600) | timestamp_custom('%H:%M') }}
```

**Impact**  
Affects all UK users during BST period (March-October) and potentially other regions using daylight saving.
